# Работа с Excel

Материалы:
* Макрушин С.В. Лекция 7: Работа с Excel
* https://docs.xlwings.org/en/stable/quickstart.html
* https://nbviewer.jupyter.org/github/pybokeh/jupyter_notebooks/blob/master/xlwings/Excel_Formatting.ipynb#search_text

## Задачи для совместного разбора

1. На листе "Рецептура" файла `себестоимостьА_в1.xlsx` для области "Пшеничный хлеб" рассчитать себестоимость всех видов продукции.

2. Результаты расчетов 1.1 сохранить в отдельном столбце области "Пшеничный хлеб"

3. Приблизить форматирование столбца, добавленного в задаче 2 к оформлению всей области.

4. Выполнить 3 с помощью "протягиваемых" формул.

## Лабораторная работа 7.1

1. Загрузите данные из файлов `reviews_sample.csv` (__ЛР2__) и `recipes_sample.csv` (__ЛР5__) в виде `pd.DataFrame`. Обратите внимание на корректное считывание столбца(ов) с индексами. Оставьте в таблице с рецептами следующие столбцы: `id`, `name`, `minutes`, `submitted`, `description`, `n_ingredients`

In [1]:
import pandas as pd

In [2]:
rev = pd.read_csv('reviews_sample.csv', delimiter=',')
rev

,Unnamed: 0,user_id,recipe_id,date,rating,review
0,370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...,...
126691,1013457,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
126692,158736,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
126693,1059834,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
126694,453285,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
126695,691207,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

In [3]:
# Загружаем данные из файла recipes_sample.csv и оставляем только нужные столбцы
rec = pd.read_csv("recipes_sample.csv")[['name', 'id', 'minutes', 'submitted', 'description', 'n_ingredients']]
rec

,name,id,minutes,submitted,description,n_ingredients
0,george s at the cove black bean soup,44123,90,2002-10-25,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,2003-07-26,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,2002-08-29,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,2002-07-27,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,2004-02-23,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,2007-11-25,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,2009-08-24,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,2004-11-03,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,2012-08-29,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,2008-04-15,"i've heard of the 'cookies by design' company,...",10.0

In [12]:
# Если нужно начать индексирование с 1

df = pd.read_csv("recipes_sample.csv")

# Добавление нового столбца 'Index' с индексами начиная с 1
df['Index'] = df.index + 1

# Установка 'Index' в качестве индекса DataFrame
df.set_index('Index', inplace=True)

df

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
Index,,,,,,,,
1,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
2,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
3,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
4,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
5,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29996,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29997,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29998,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29999,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
30000,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

2. Случайным образом выберите 5% строк из каждой таблицы и сохраните две таблицы на разные листы в один файл `recipes.xlsx`. Дайте листам названия "Рецепты" и "Отзывы", соответствующие содержанию таблиц.

In [5]:
# Выбор случайных 5% строк из DataFrame
sample_rev = rev.sample(frac=0.05)
sample_rec = rec.sample(frac=0.05)

In [6]:
sample_rev

,Unnamed: 0,user_id,recipe_id,date,rating,review
24769,774160,1168939,128956,2010-07-12,4,This is good for vegetable soup... I think I w...
72706,131435,1179225,76540,2011-10-31,5,What a treat! I hardly ever make fried food or...
33950,435626,386585,107443,2009-05-22,5,Simply delicious and authentic. I made it exa...
11175,664049,106797,35038,2005-11-15,5,I have never liked the standard American potat...
96147,431661,1019463,335395,2011-12-24,5,I LOVE this recipe! I have brought it to two ...
...,...,...,...,...,...,...
125030,1108681,269331,273953,2009-05-30,5,Wow this is almost better than banana bread; s...
29499,328071,128473,320991,2014-04-29,5,What a lovely lightly flavored mocha coffee. ...
122906,781914,239758,362056,2013-06-05,4,"Lovely recipe. I used two small pears, 4 ounce..."
83921,898034,424680,200449,2007-05-12,5,"Made for PAC, Spring 2007 ~ I'm reluctant to a..."
65448,1108690,22724,30358,2002-08-07,5,Your right...my pasta came out PERFECT! It wa...

In [7]:
sample_rec

,name,id,minutes,submitted,description,n_ingredients
2961,bet you can t eat just one shrimp,213352,1455,2007-02-23,the perfect spanish tapas! these disappear qui...,11.0
27673,toasted ham and cheese supreme,318755,15,2008-08-12,a step up from the usual grilled ham and chees...,NaN
29609,ww roasted carrots,187151,5,2006-09-20,this is the only way i will eat carrots. they ...,5.0
27699,toffee bar cookies,389577,15,2009-09-09,these are delicious bars - and so easily made ...,7.0
29605,ww molasses grilled chops with horseradish sauce,210334,25,2007-02-10,this is from an old weight watchers cookbook c...,10.0
...,...,...,...,...,...,...
9345,deluxe spaghetti pie,372248,60,2009-05-16,defintely not for those watching their calorie...,13.0
730,angie s just right salad dressing,85354,5,2004-02-29,this is definitely a favorite of mine. unlike ...,NaN
14929,jean s quick chili,51126,30,2003-01-13,this recipe is a variation of a recipe in a lo...,8.0
16339,lollipop cookies,159672,60,2006-03-13,these look really cute. kids will love them.,NaN
9913,easy chicken kiev baked,241178,80,2007-07-18,"there's a few recipes on zaar for this, but th...",10.0

In [8]:
import xlwings as xw

wb = xw.Book('recipes.xlsx')
wb.sheets.add()  # Добавляем новый лист

In [9]:
wb.sheets[0].name = 'Рецепты'
sht1 = wb.sheets['Рецепты']

wb.sheets[1].name = 'Отзывы'
sht2 = wb.sheets['Отзывы']

In [10]:
sht1.range('A1').value = sample_rec
sht2.range('A1').value = sample_rev

In [11]:
# выравниваем ширину строки
sht1.autofit()
sht2.autofit()

3. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_assign`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи присваивания массива значений диапазону ячеек.

In [14]:
wb.sheets['Рецепты'].activate() # делаем активным лист Рецепты, т.е. sht1

# Получаем данные из столбца minutes
minutes_column = sht1.range('D2').expand('down').value     # sht1.range('minutes').value

# Умножаем значения на 60
seconds_column = [value * 60 for value in minutes_column]

# Добавляем новый столбец в Excel
sht1.range('H2').options(transpose=True).value = seconds_column

# sht1.range('G2').expand('down').offset(row_offset=1).value = new_column
# offset(row_offset=1): 
# для получения доступа к ячейке в той же колонке, но на одну строку ниже относительно текущей ячейки

In [15]:
sht1.range('H1').value = 'seconds_assign'
sht1.autofit()

4. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_formula`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи формул Excel.

In [17]:
# ПЕРЕДЕЛАТЬ!

for i in range(1, len(sht1.range('D2').expand('down')) + 1):
    sht1.range('I' + str(i)).formula = '=$D$' + str(i) + '*60'

In [18]:
sht1.range('I1').value = 'seconds_formula'

In [19]:
sht1.autofit()

5. Сделайте названия всех добавленных столбцов полужирными и выровняйте по центру ячейки.

In [22]:
sht1.range('A1').expand('right').api.Font.Bold = True
sht1.range('A1').expand('right').api.HorizontalAlignment = True

AttributeError: Unknown property, element or command: 'Font'

6. Раскрасьте ячейки столбца `minutes` в соответствии со следующим правилом: если рецепт выполняется быстрее 5 минут, то цвет - зеленый; от 5 до 10 минут - жёлтый; и больше 10 - красный.

- (255, 0, 0) красный цвет
- (0, 255, 0) зеленый цвет
- (0, 0, 255) синий цвет
- (255, 255, 0) желтый цвет

In [21]:
minutes = sht1.range('D2').expand('down')
for i in minutes:
    if i.value < 5:
        i.color = (0, 255, 0) # зеленый цвет
    elif 5 <= i.value <= 10:
        i.color = (255, 255, 0) # желтый цвет
    elif i.value > 10:
        i.color = (255, 0, 0) # красный цвет

7. Добавьте на лист `Рецепты`  столбец `n_reviews`, содержащий кол-во отзывов для этого рецепта. Выполните задание при помощи формул Excel.

In [27]:
sht1.range('J1').value = 'n_reviews'
recps = sht1.range('C2').expand('down').options(ndim=1).value
rgn_name = sht2.range('D2').expand('down').address
c = 1
for i in recps:
    c += 1
    sht1.range('J' + str(c)).value = sht2.formula = f'=COUNTIF(c:c, {i})'

In [25]:
sht1.autofit()

## Лабораторная работа 7.2

8. Напишите функцию `validate()`, которая проверяет соответствие всех строк из листа `Отзывы` следующим правилам:
    * Рейтинг - это число от 0 до 5 включительно
    * Соответствующий рецепт имеется на листе `Рецепты`
    
В случае несоответствия этим правилам, выделите строку красным цветом

In [28]:
def validate(rating):
    wb.sheets['Отзывы'].activate() # делаем активным лист Отзывы, т.е. sht2
    try:
        assert 0 <= rating <= 5, 'Рейтин должен быть в пределах от 0 до 5!'
        # Получаем данные из столбца minutes
        rating_column = sht2.range('rating').value    # sht2.range('F2').expand('down').value
        for ind,val in enumerate(rating_column):
            if val != rating:
                sht2.range(f'A{ind+2}').expand('right').color = (255, 0, 0)
    except AssertionError as err:
        print(err)

In [29]:
validate(10)

Рейтин должен быть в пределах от 0 до 5!

In [30]:
validate(5)

9. В файле `recipes_model.csv` находится модель данных предметной области "рецепты". При помощи пакета `csv` считайте эти данные. При помощи пакета `xlwings` запишите данные на лист `Модель` книги `recipes_model.xlsx`, начиная с ячейки `A2`, не используя циклы. Сделайте скриншот текущего состояния листа и прикрепите в ячейку ноутбука.

In [33]:
# определяем разделитель в csv файле
with open('recipes_model.csv', 'r') as file:
    first_line = file.readline()
    dialect = csv.Sniffer().sniff(first_line)
    print('Разделитель в файле:', dialect.delimiter)

Разделитель в файле:

In [34]:
wb1 = xw.Book('recipes_model.xlsx')
wb1.sheets[0].name = 'Модель'
sht3 = wb1.sheets['Модель']

In [37]:
with open('recipes_model.csv') as file:
    sht3.range('A2').value = list(csv.reader(file, delimiter='	'))

In [47]:
# к сожалению, не работает

from PIL import ImageGrab  # Импорт библиотеки для захвата изображения экрана

# Выбираем нужный лист и диапазон ячеек
range_to_capture = sht3.range('A2:I18').expand()

# Захватываем скриншот диапазона ячеек
img = ImageGrab.grab(bbox=(range_to_capture.left, range_to_capture.top, range_to_capture.width, range_to_capture.height))

# Сохраняем скриншот в файл
img.save('screenshot.png')

# Вставляем скриншот в Excel (в ячейку A20)
sht3.pictures.add(img, name='Screenshot', update=True, left=sht3.range('A20').left, top=sht3.range('A20').top)

TypeError: 'float' object cannot be interpreted as an integer

10. При помощи пакета `xlwings` добавьте в столбец J формулу для описания столбца на языке SQL. Формула должна реализовывать следующую логику:

    1\. в начале строки идут значения из столбцов В и C (значение столбца С приведено к верхнему регистру), разделенные пробелом
    
    2\. далее идут слова на основе столбца "Ключ"
        2.1 если в столбце "Ключ" указано значение "PK", то дальше через пробел идет ключевое слово "PRIMARY KEY"
        2.2 если в столбце "Ключ" указано значение "FK", то дальше через пробел идет ключевое слово "REFERENCES", затем значения столбцов H и I в формате "название_таблицы(название_столбца)"
        
    3\. если в столбце "Обязательно к заполнению" указано значение "Y" и в столбце "Ключ" указано не "PK", то дальше через пробел идет ключевое слово "NOT NULL".

Заполните этой формулой необходимое количество строк, используя "протягивание". Количество строк для протягивания определите на основе данных.

Сделайте скриншот текущего состояния листа и прикрепите в ячейку ноутбука.

In [ ]:
# ???

11. При помощи пакета `xlwings` измените стилизацию листа `Модель`.
* для заголовков добавьте заливку цвета `00ccff`
* примените автоподбор ширины столбца;
* сделайте шрифт заголовков полужирным;
* добавьте таблице автофильтр.

Сделайте скриншот текущего состояния листа и прикрепите в ячейку ноутбука.

In [48]:
# окрашивание заголовков столбцов
sht3.range('A2').expand('right').color = (0,204,255)

# приминение автоподбора ширины столбца
sht3.autofit()

# шрифт заголовков полужирный

# автофильтр

12. Посчитайте количество атрибутов для каждой из сущностей. Создайте лист `Статистика` и запишите в него результат группировки, начиная с ячейки "А1". Визуализируйте полученный результат при помощи столбчатой диаграммы. Сохраните полученную визуализацию на лист `Статистика`, начиная с ячейки "E2".  Сделайте скриншот листа `Статистика` и прикрепите в ячейку ноутбука.

* Вы можете воспользоваться методами для визуализации, которые поставляются вместе с объектами `pandas` (см. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot)